---
- name: Define variables.
  set_fact:
    project_owner: "{{ ansible_user }}"
  when: project_owner is not defined

- name: Define variables.
  set_fact:
    owner_group: "{{ ansible_user }}"
  when: owner_group is not defined
# tasks file for project setup
- name: Register release variable
  shell: date +%Y%m%d%H%M%S
  register: project_deploy_date

- name: Create the release directory.
  file:
    state=directory
    path={{deploy.project.root}}/releases/{{project_deploy_date.stdout}}

- name: Create the shared directory.
  file:
    state=directory
    path={{deploy.project.root}}/shared

- name: Change owner
  file: owner="{{project_owner}}" group="{{owner_group}}" recurse=yes dest="{{deploy.project.root}}"